# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MTG MIR config list
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A list of conferences related to the Music Technology Group
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mtg_upf
github_username:  mtg

# Build settings
markdown: kramdown
collections:
 - conferences
